Add geometry primitives and triangle clipping
cutehater/3d-renderer pull request #2
Opened 2024-02-07 13:32 UTC by cutehater

2024-02-26 13:25 UTC, DimaTrushin requested changes
Ты не верно подключил glm в качестве git submodule из-за этого ся библиотека залилась в репозиторий. У меня все тормозит, я не могу ничего откомментировать.

2024-03-04 10:29 UTC, DimaTrushin requested changes
Обрати внимание, что я не повторял замечания. Если одна и та же ошибка всречалась несколько раз, я комментировал лишь единожды. Потому я ожидаю, что ты поправишь все аналогичные замечания всюду.

Поздравляю, ты первая, кто справился с тем, чтобы удалить неверно залитый в репозиторий submodule не снося весь репозиторий. Это успех.

Обрати внимание на лажу с геометрическими проверками. И я понятия не имею, что у тебя делает функция пересекающая треугольник и плоскость.

2024-03-04 10:29 UTC, DimaTrushin commented on .gitignore
> +.vscode/
Добавь пустую строку в конце каждого файла. Дело в том, что гит на это ругается и пользователь твоего репозитория будет видеть сообщения об ошибках от гита. Не делай так.
Добавить в clang-format правило:
InsertNewlineAtEOF: true

2024-03-04 10:29 UTC, DimaTrushin commented on CMakeLists.txt
> +add_subdirectory(include)
Я не вижу этой дирректории в списке папок в git репозитории. Ты сюда не всю загрузила?

2024-03-04 10:29 UTC, DimaTrushin commented on src/primitives.h
> +    // constructor for interpolated vertex inside triangle
1) Комментарии это всегда признак ошибки в работе над кодом. В данном случае у тебя проблема в том, что тебе не понятно по аргументам конструктора, что ты строишь, и потому ты добавляешь комментарий. Вместо этого надо завести статическую функцию с говорящим именем, например так:
```cpp
static Vertex interpolate(const Triangle& triangle, const dvec4& ???);
```
И тогда тебе надо будет всего лишь звать Vertex::interpolate(triangle, ??);
2) За что отвечает pos? Это position как я понял. Во-первых, НЕ сокращай названия. Во-вторых, как именно характеризуется позиция? Почему это вектор с 4 компонентами? Если это точка в глобальных координатах, то гарантируется, что она лежит в треугольнике или эта функция должна проверить на корректность данные? Если это локальные координаты, то в каком базисе? Почему так много координат? Почему их аж 4?

Вообще в таком случае используют барицентрические координаты, то есть представляют точку внутри так
p = a v1 + b v2 + c v3;
где a + b + c = 1 и a, b, c >= 0. Тогда ты можешь однозначно адресовать точку внутри треугльника независимо от того где и в каких координатах он представлен.

2024-03-04 10:29 UTC, DimaTrushin commented on src/primitives.h
> +    Vertex(const glm::dvec4 &pos, const glm::dvec3 &norm,
Не используй сырые типы просто так, заведи using-ги. Либо глобальные на весь проект и собери их в отдельном хедере или для каждого класса вводи эти юзинги в начале. Например
```cpp
using Vector4 = glm::dvec4;
```
Тогда ты не будешь зависить от этого имени всюду и изменение библиотеки приведет лишь к изменению юзингов. А кроме того, ты не будешь все время дергать имена через пространство имен и лишние квалификаторы доступа вроде ::. Плюс имена не будут зависеть от выбора библиотеки.

2024-03-04 10:29 UTC, DimaTrushin commented on src/primitives.h
> +    Vertex(const glm::dvec4 &pos, const glm::dvec3 &norm,
Вопрос, типы glm::dvec2, 3, 4 все хранят по адресу объекта или на куче? Если первое, то у тебя нормальная сигнатура конструктора, если второе (что вряд ли), то нужны sink arguments.

2024-03-04 10:29 UTC, DimaTrushin commented on src/primitives.h
> +    Vertex() = default;
Если делаешь дефолтный конструктор, то правила приличия говорят, что надо всем полям класса указать дефолтные значения. Только их не надо делать магическими константами, для этого нужно завести constexpr статические значения для них и присводить всем полям при объявлении.

2024-03-04 10:29 UTC, DimaTrushin commented on src/primitives.h
> +    glm::dvec4 getPosition() const;
Я правильно понимаю, что это намерено возвращается by value, потому что у тебя просто возвращается 4 double без аллокаций и это дешево?

2024-03-04 10:29 UTC, DimaTrushin commented on src/primitives.h
> +    std::vector<Vertex> getVertices() const;
Вот это уже плохо. НИКОГДА не возвращай контейнеры by value. Это потенциально супер супер супер дорого. Возвращай их по константной ссылке. Во-первых, так у тебя конструируется копия вектора. Во-вторых, у тебя аллоцируется память на куче. В-третьих, у тебя копируется куча данных.

2024-03-04 10:29 UTC, DimaTrushin commented on src/primitives.h
> +    std::vector<Vertex> vertices_;
Какого хрена тут std::vector, а не std::array<double, 3>??? У тебя же не может быть больше 3 вершин у треугольника по определению! Если тебе надо облегчить локальную часть треугольника можешь сделать std::unique_ptr<std::array<double, 3>>, но тогда надо поддерживать состояние, когда у треугольника ничего нет внутри.

2024-03-04 10:29 UTC, DimaTrushin commented on src/primitives.h
> +    std::vector<double> getBarycentricWeights(glm::dvec3 p) const;
Почему не std::array<double, 3>? Кроме того, еще лучше завести структуру
```cpp
struct BaricentricCoordinates {
  std::array<double, 3> coordinates;
};
```
Или сделать поля с именами
```cpp
struct BaricentricCoordinates {
  double alpha;
  double beta;
  double gamma;
};
```
Все зависит от того, что ты хочешь.

Кроме того, тут тоже можно симулировать контейнер, как и для случая позиций. Вопрос  в том, как лучше.

2024-03-04 10:29 UTC, DimaTrushin commented on src/primitives.h
> +    std::vector<glm::dvec3> getVerticesPositions() const;
Вместо создания вектора с позициями я бы создал прокси контейнер, а именно
```cpp
class TrianglePositionsView {
  using Container = const std::vector<Vertex>;

  // приватный конструктор, чтобы никто кроме Triangle не мог создать этот объект.
  friend class Triangle ;
  TrianglePositionsView(Container* host) : host_(host) {}

  // делаем свой итератор, чтобы он бежал по вектору из вершин, но разыменовывался в
  // вектора из позиций
  class ConstIterator {
    using HostIterator = Container::const_iterator;
  public:
    ConstIterator(HostIterator iter) : iter_(iter) {}
    // тут можно возвращать по ссылке, но тогда надо, чтобы и getPosition возвращал по ссылке
    // нужна консистентность, чтобы не было всяких дурацких ситуаций.
    dvec3 operator*() const {
      return iter->getPostion();
    }
    // остальные операторы обслуживающие твой итератор: операции ++, оператор ->, операторы сравнения.
  private:
    HostIterator iter_;
  };
public:
  constIterator begin() const;
  constIterator end() const;
private:
  Container* host_;
};
```
После этого делаешь метод
```cpp
TrianglePositionsView getVerticesPositions() const {
  return TrianglePositionsView(&vertices_);
}
```
Такой подход помогает тебе симулировать контейнер из объектов, которого у тебя нет синтаксически, но который есть логически.

2024-03-04 10:29 UTC, DimaTrushin commented on src/primitives.h
> +    Plane(const glm::dvec3 &norm, const glm::dvec3 &p);
На это замечание можно забить в целом сейчас. Но вообще говоря это плохой интерфейс. Когда у тебя два одинаковых типо подряд играют разную роль, то ты можешь легко перепутать, кто из этих векторов норма, а кто точка. Причем ты это перепутаешь именно когда будешь вызывать этот конструктор.
```cpp
Plane p(p, norm);
```
Ничто не мешает тебе так написать и оно даже скомпилируется и приведет к неожиданным результатам. Обычно тут делают типизированных гардов. Я рассказывал на курсе по плюсам как это делать. Но думаю пока можно забить.

2024-03-04 10:29 UTC, DimaTrushin commented on src/primitives.cpp
> +// assuming the last coordinate is equal to 1
Компилятор не понимает комментариев. А программист не заметит. Что ты хочешь этим комментарием тут сказать? Если это инвариант класса, то проверяй его assert-ами: в конце каждого конструктора и в конце каждого мутирующего метода. Так же во всех методах стоит проверять preconditions на аргументы.

2024-03-04 10:29 UTC, DimaTrushin commented on src/primitives.cpp
> +    std::vector<double> w = triangle.getBarycentricWeights(pos);
А что если pos находится вне треугольника? Более того, из-за ошибок округления это происходит с вероятностью 1 (но может быть на небольшую величину). В общем мне не нравится две вещи: 1) с таким интерфейсом у тебя есть preconditions на точку pos, 2) у тебя плохой неустойчивый к вычислительной точности интерфейс. Почему сразу не принимать барицентрические координаты?

2024-03-04 10:29 UTC, DimaTrushin commented on src/primitives.cpp
> +    std::vector<Vertex> v = triangle.getVertices();
getVertices дорогая операция, которая возвращает копию данных. Тебе это тут не нужно. Ты потом вектор v не используешь.

2024-03-04 10:29 UTC, DimaTrushin commented on src/primitives.cpp
> +    : vertices_({a, b, c}){};
1) Во-первых, можно написать vertices_{a, b ,c}, и если сделать std::array<double, 3>, то у тебя будет aggregate initialization, что сэкономит вызов лишнего конструктора. Прочти вот тут:
https://en.cppreference.com/w/cpp/language/aggregate_initialization
Во-вторых, у тебя должны быть preconditions на вершины, они должны быть разные!

2024-03-04 10:29 UTC, DimaTrushin commented on src/primitives.h
> +    std::vector<double> getBarycentricWeights(glm::dvec3 p) const;
Ты не консистентно принимаешь значения аргументов. То ты их принимаешь by value, то by const reference. Определись какой из подходво лучше и пользуйся только одним. Будь консистентной.

2024-03-04 10:29 UTC, DimaTrushin commented on src/primitives.cpp
> +                         glm::dot(q1, q2) * glm::dot(q1, q2));
Вот тут явно не хватает дополнительной функции для вычисления квадрата площади параллелограмма. Или может быть даже для вычисления определителя матрицы Грама, или даже чего-то более общего вида, что у тебя тут везде встречается, чтобы не писать эту функцию постоянно.

2024-03-04 10:29 UTC, DimaTrushin commented on src/primitives.cpp
> +    : Plane(glm::normalize(glm::cross(c - a, b - a)), a){};
У тебя есть preconditions на точки. Вдруг какие-то совпадают!

2024-03-04 10:29 UTC, DimaTrushin commented on src/primitives.cpp
> +    : norm_(norm), distFromOrigin_(distFromOrigin){};
- Preconditions на norm.
- Расстояние может быть отрицательным? Если да, то плохое название. Нужно написать oriented.

2024-03-04 10:29 UTC, DimaTrushin commented on src/primitives.cpp
> +    : norm_(norm), distFromOrigin_(glm::dot(p, norm)){};
glm::dot(p, norm) -- НЕ расстояние до начала координат.
1) Во-первых, это число ориентировано и имеет знак
2) Во-вторых, оно равно расстоянию по модулю только если norm имеет единичную длину. У тебя все эти инварианты поддерживаются? Если нет, то это делает не то что надо. Если да, то где все assert-ы, которые это проверяют?

2024-03-04 10:29 UTC, DimaTrushin commented on src/intersection.h
> +intersectTrianglePlane(const Primitives::Triangle &triangle,
Как ты получаешь при пересечении треугольника и плоскости набор треугольников? Может быть это clip функция, которая делает клиппинг?

2024-03-04 10:29 UTC, DimaTrushin commented on src/intersection.cpp
> +    double denominator = glm::dot(plane.getNorm(), ray.getDirection());
Что это за хрень? Названия переменных вообще ни о чем не говорят. В чем смысл этих знаменатели и числителя? Что за условие тут проверяется?

2024-03-04 10:29 UTC, DimaTrushin commented on src/intersection.cpp
> +    if (glm::equal(denominator, 0.0, glm::epsilon<double>())) {
Вместо нечитаемого условия под if сделай функцию, которая проверяет нужное условие. Например areNormalsOnTheSameLine или что-то в этом духе. Вырази это словами и вызови эту функцию тут.

2024-03-04 10:29 UTC, DimaTrushin commented on src/intersection.cpp
> +            return Intersection{Intersection::Type::NonIntersect};
А это что за случай?

2024-03-04 10:29 UTC, DimaTrushin commented on src/intersection.cpp
> +        intersectRayPlane(ray, Primitives::Plane(triangle));
Вот тут лишняя потенциально не дешовая операция по построению временной плоскости, которая после этого вызова не нужна и зависит от тех же данных, что и треугольник. Думаю это можно сделать лучше.

2024-03-04 10:29 UTC, DimaTrushin commented on src/intersection.cpp
> +            triangle.getBarycentricWeights(intersection.point);
- Это не корректный алгоритм. Если у тебя луч лежит в плоскости и его вершина не лежит в треугольнике, но он все равно пересекает треугольник. Потому что в случае если луч лежит в плоскости, ты тут читаешь его вершину и проверяешь лежит ли вершина луча в треугольнике, что является не верной проверкой.
- Думаю надо добавить функцию для пересечения луча с полуплоскостью. Тогда это решит проблему с треугольником, ты просто проверишь для трех полуплоскостей условие.

2024-03-04 10:29 UTC, DimaTrushin commented on src/intersection.cpp
> +intersectPlaneTriangle(const Primitives::Triangle &triangle,
У тебя функция длиной почти в 70 строк! Что тут происходит? Это даже читать невозможно. Хотя бы нет вложенных scope. Отрефакторить.

2024-04-07 10:52 UTC, cutehater commented on CMakeLists.txt
> +add_subdirectory(include)
Это старое разбиение было, потом нашла в мануале что не надо инклуды и сурсы делить. Уберу

2024-04-07 12:05 UTC, cutehater commented on src/primitives.h
> +    Vertex(const glm::dvec4 &pos, const glm::dvec3 &norm,
Да вроде как по адресу

2024-04-07 12:09 UTC, cutehater commented on src/primitives.h
> +    glm::dvec4 getPosition() const;
Верно

2024-04-08 11:49 UTC, cutehater commented on src/primitives.h
> +    std::vector<glm::dvec3> getVerticesPositions() const;
Не уверена была, как лучше, поэтому всю простые однострочные методы итераторов написала прямо в хедере. Если надо будет, унесу в cpp.

2024-04-08 12:57 UTC, cutehater commented on src/primitives.cpp
> +    std::vector<Vertex> v = triangle.getVertices();
Сделала возврат по ссылке

2024-04-08 12:58 UTC, cutehater commented on src/primitives.h
> +    std::vector<double> getBarycentricWeights(glm::dvec3 p) const;
Ой, это я случайно

2024-04-08 13:15 UTC, cutehater commented on src/primitives.cpp
> +    std::vector<Vertex> v = triangle.getVertices();
Вроде использую, я после этого все свойства вершины, кроме позиции, пересчитываю через свойства соответствующих вершин треугольника + барицентрические координаты

2024-04-08 13:24 UTC, cutehater commented on src/primitives.cpp
> +    std::vector<double> w = triangle.getBarycentricWeights(pos);
Потому что мы хотим на выходе вершину с координатой position получить, а координату не очень удобно восстанавливать только по барицентрическим координатам. А одновременно и position, и барицентрические координаты передавать как будто излишне. И мы хотим эту функцию только для вершин внутри какого-то треугольника вызывать, чтобы назначить им цвет, текстуру и т.д. Пока так оставила, добавила проверку на то, что вершина внутри треугольника находится; возможно потом пойму, что лучше другой интерфейс и поменяю удобное придумаю.

2024-04-08 14:46 UTC, cutehater commented on src/intersection.h
> +intersectTrianglePlane(const Primitives::Triangle &triangle,
Да, это клиппинг, что-то я сама запуталась немного

2024-04-12 09:38 UTC, cutehater commented on src/intersection.cpp
> +            return Intersection{Intersection::Type::NonIntersect};
Когда луч лежит "за" плоскостью и не пересекается с ней

2024-04-12 09:42 UTC, cutehater commented on src/intersection.cpp
> +        intersectRayPlane(ray, Primitives::Plane(triangle));
Давай пока так оставлю, но я запомнила, подумаю, как это сделать, чтобы и структура кода была не костыльная, а читаемая, и лишний раз конструировать плоскость не приходилось

2024-04-12 10:02 UTC, cutehater commented on src/intersection.cpp
> +            triangle.getBarycentricWeights(intersection.point);
Окей, эта функцию планируется использовать только в clippingе, где, если вдруг треугольник лежит на самой плоскости, мы забиваем и говорим что он лежит "за" ней (hidden) до того, как пытаться с ней пересечь. Переименовала функцию и добавила assert на Coincide случай.

2024-04-12 11:42 UTC, cutehater commented on src/intersection.cpp
> +intersectPlaneTriangle(const Primitives::Triangle &triangle,
Блин ну у неё размер не сильно меньше стал... Но я постаралась нормально отрефакторить, чёто в отдельные функции повыносить и пару вложенных скоупов добавила.

2024-04-12 11:54 UTC, cutehater commented on src/intersection.cpp
> +            triangle.getBarycentricWeights(intersection.point);
А я чёто сама не поняла, зачем она мне нужна, пока просто убрала

2024-04-12 21:22 UTC, cutehater commented
Я временно убрала освещение+текстуру. Добавлю позже, если успею 🙏

2024-04-15 15:34 UTC, cutehater commented
Вообщем я очень жёстко всё поменяла) Это я 🤡
На данный момент реализованы классы примитивов (вершина + треугольник), объекта, мира и камеры (преобразование в координаты камеры + клиппинг (обрезаю только по near плоскости) + проективные преобразования)
Вершина хранится в виде цвет + 4 координаты (3 - положение вершины + гомогенная координата), как мне показалось, удобнее везде в коде вплоть до проекции на экран хранить 4 координаты, переопределив для них необходимые операции, чем постоянно переключаться туда-сюда с трёх на четыре

2024-04-17 16:40 UTC, cutehater commented
Вот теперь приложение запускается и даже умеет в корректный цветовой градиент (потестила на пирамидке ручками). Но со сдвигом камеры всё плохо (не работает), а иногда и просто на добавлении объектов падает. Надо разбираться

2024-04-18 09:27 UTC, cutehater commented
Я разобралась со сдвигом камеры, он работает. Но пока куча артефактов при клиппинге, если объект заезжает за переднюю плоскость видимости

2024-04-19 10:42 UTC, cutehater commented
На этом этапе камера нормально ездит и поворачивается, корректно работает интерполяция цвета. Пока не очень с клиппингом near плоскости. Ещё как-то странно при движении камеры вверх-вниз (я тестила на пирамидке, и почему-то, когда камера поднимается вверх, то начинает становиться дно пирамидки, а когда вверх - нет, хотя должно быть наоборот. В остальном +- рабочий код

2024-05-08 13:37 UTC, DimaTrushin requested changes
Обрати внимание, что я не повторял замечания. Если одна и та же ошибка всречалась несколько раз, я комментировал лишь единожды. Потому я ожидаю, что ты поправишь все аналогичные замечания всюду.

Выглядит очень неплохо. Остались небольшие замечания.

Еще судя по всему у тебя не всегда прогоняется clang-format, настрой ide так, чтобы он срабатывал на сохранение файлов.

2024-05-08 13:37 UTC, DimaTrushin commented on .gitignore
> +src/MakeFile
Добавь пустую строку в конце каждого файла. Дело в том, что гит на это ругается и пользователь твоего репозитория будет видеть сообщения об ошибках от гита. Не делай так.
Добавить в clang-format правило:
InsertNewlineAtEOF: true

2024-05-08 13:37 UTC, DimaTrushin commented on examples/cubes.cpp
> +    }
Вот это все должно быть в конструкторе app. Потому что app это НЕ контейнер, это более абстрактная вещь. Это контекст твоего приложения, где все существует. Вне него вообще не должно ничего существовать в твоем приложении.
Если хочешь создавать разные application с разным набором компонент, то передавай в конструкторе Application инициализатор, например функцию которая принимает world по ссылке и в которой указывается чем наполнить этот самый мир. Или просто собирай Application с помощью policy based design. В любом случае такой низкоуровневый код не должен лежать вне application.

2024-05-08 13:37 UTC, DimaTrushin commented on examples/cubes.cpp
> +    ScratchRenderer::Application app;
У тебя не отключены exception, потому надо поставить блок на них. Это делается так
```cpp
#include "Application.h"
#include "Except.h"

int main() {
  try {
    ScratchRenderer::Application app;
    app.run();
  } catch(...) {
    except::react();
  }
  return 0;
}
Except.h
namespace except {
void react();
}
Except.cpp
#include "Except.h"

namespace except {
void react() {
  try {
    throw;
  } catch(std::exception& e) {
    // обрабатываешь известные исключения
  } catch(...) {
    // обрабатываешь незивестные исключения
  }
}
}
```
То есть main ничего сама не делает, она всю работу делегирует другим. Задача main заниматься оркестровкой. Она даже исключения сама не обрабатывает, но при этом не дает им улететь в операционку, чтобы уметь отличить проблемы в операционке от проблем в твоем приложении.

2024-05-08 13:37 UTC, DimaTrushin commented on examples/cubes.cpp
> +const double kCubeDistanceFromOrigin = 17;
1) Это какая-то локальная константа связанная с настройками создания сцены. Ей тут не место, перенеси ее куда-нибудь в настройки объектов отвечающих за хранение объектов. 
2) И еще, глобальные константы лучше делать constexpr.
3) И еще, если делаешь глобальные константы, то лучше добавлять префикс g в начале, чтобы понимать, что это глобальное данное.

2024-05-08 13:37 UTC, DimaTrushin commented on src/application.h
> +    void addObject(Object &&object);
Убрать. Лучше поправь конструктор так
```cpp
using Signature = void(World&);
using FunctionPtr = Signature*;
Application(FunctionPtr* init) {
  init(wrold_);
}
```
И уже метод init, который ты передаешь в конструкторе будет инициализировать твое приложение. То есть можно будет писать так
```cpp
#include "Application.h"
#include "Except.h"
#include "CubeInit.h"

int main() {
  try {
    ScratchRenderer::Application app(cube_init);
    app.run();
  } catch(...) {
    except::react();
  }
  return 0;
}
```

2024-05-08 13:37 UTC, DimaTrushin commented on src/application.cpp
> +        renderer_.renderFrame(window_, world_, camera_);
Мне не нравится дизайн. У тебя рендерер знает про window_. Это плохо, что ядро программы знает про gui часть. Лучше было бы сделать что-то вроде
```cpp
Image image = renderer_.renderFrame(world_, camera_);
window_.draw(image);
```
Так связь между ядром и gui будет только в формате картинки и будет более явно виден поток данных. Вторая строчка весьма условная.

2024-05-08 13:37 UTC, DimaTrushin commented on src/application.cpp
> +        }
Нарушение уровня абстракции. У тебя тут идет низкоуровневая работа, а ниже в строчках 30 и 31 у тебя вызываются высокоуровневые функции. Я бы это завернул в метод handleKeyboardInput();

2024-05-08 13:37 UTC, DimaTrushin commented on src/application.cpp
> +        }
Нарушение уровня абстракции. Я бы завернул это во вспомогательный метод, который например возвращает bool и выходит, например
```cpp
if (isWindowClosing(event)) {
  return;
}
```

2024-05-08 13:37 UTC, DimaTrushin commented on src/application.cpp
> +    : renderer_(configuration::kWindowWidth, configuration::kWindowHeight), world_(), camera_(),
Дефолтные конструкторы можно не указывать. Убери их.

2024-05-08 13:37 UTC, DimaTrushin commented on src/application.cpp
> +void Application::addObject(Object &&object) { world_.addObject(std::move(object)); }
убрать.

2024-05-08 13:37 UTC, DimaTrushin commented on src/application.h
> +    struct Handler {
Когда я это увидел сразу подумал, что сейчас будет какой-то интересное решение.

2024-05-08 13:37 UTC, DimaTrushin commented on src/storage2d.h
> +    size_t cols_;
Достаточно хранить только cols_, потому что rows_ восстанавливается как data_.size() / cols_.

2024-05-08 13:37 UTC, DimaTrushin commented on src/storage2d.h
> +template <typename T> class Storage2D {
Кстати, можно было использовать Eigen::Array или даже Eigen::Matrix для такого хранилища. Но и так тоже хорошо.

2024-05-08 13:37 UTC, DimaTrushin commented on src/storage2d.h
> +    Storage2D(size_t rows, size_t cols) : rows_(rows), cols_(cols), data_(rows * cols){};
Такое ощущение, что к этому файлу не применен clang-format. Настрой свою ide так, чтобы она применяла clang-format на сохранение файла. Тогда тебе не придется никогда об этом беспокоиться.

2024-05-08 13:37 UTC, DimaTrushin commented on src/vector4.h
> +class Vector4 : public glm::dvec4 {
Неплохая идея сделать такую обертку. Еще как вариант можно просто добавлять внешние friend операции в пространство имен, где лежит glm::dvec4. Но так конструкторы не добавишь. Но это часто и не надо, потому что named constructor idiom часто лучше.

2024-05-08 13:37 UTC, DimaTrushin commented on src/vector4.cpp
> +    *this = *this + other;
Плохая тема определять inplace операцию через бинарную, когда inplace имеет более эффективную имплементацию.

2024-05-08 13:37 UTC, DimaTrushin commented on src/vector4.cpp
> +Vector4::Vector4(const glm::dvec4 &v) : glm::dvec4(v.x, v.y, v.z, v.w) {}
А не хочешь поддерживать инвариант, что w = 1 и добавить тут normalize в конструкторе и вообще запретить создание вектора с нулевой w. Кроме того, наличие такого инварианта позволит тебе упростить формулы для операций арифметических, ты сможешь избавиться от постоянного деления на w.

2024-05-08 13:37 UTC, DimaTrushin commented on src/vector4.cpp
> +    assert(!glm::equal(v.w, 0.0, Epsilon) && "w-coordinate shouldn't be null");
еще надо assert на то, что k не ноль.

2024-05-08 13:37 UTC, DimaTrushin commented on src/vector4.cpp
> +    assert(!glm::equal(this->w, 0.0, Epsilon) && "w-coordinate shouldn't be null");
не используй this при обращении к полям класса.

2024-05-08 13:37 UTC, DimaTrushin commented on src/object.cpp
> +        triangles_[i] = Primitives::Triangle::linearTransform(translatonMatrix, triangles_[i]);
Я заметил, что у тебя много не inplace операций, которые можно было бы заменить inplace операциями. Это в целом может улучшить производительность.

2024-05-08 13:37 UTC, DimaTrushin commented on src/object.h
> +    Object() = default;
А ты точно хочеш разрешить дефолтный объект? А то у тебя потом нет никакого способа его модифицировать. Зачем такое надо?

2024-05-08 13:37 UTC, DimaTrushin commented on src/global_usings.h
> +static const sf::Color DefaultColor = sf::Color::White;
Вот эта константа вряд ли должна быть глобальной. Она у тебя скорее всего определяет дефолтный цвет фона. А это уже настрока рендерера. Думаю стоит перенести туда.

2024-05-08 13:37 UTC, DimaTrushin commented on src/global_usings.h
> +static const sf::Color DefaultColor = sf::Color::White;
Не делай в h файлах статические объявления. У этого происходит такой эффект. Компилятор помещает эту переменную в anonymous namespace и потом делает юзинг этого неймспейса. То есть получается, что в каждой единице трансляции (в каждом cpp файле, который инклудит этот файл) создается отдельная копия этой переменной. Это просто раздувает бинарник и не имеет никакого смысла.

2024-05-08 13:37 UTC, DimaTrushin commented on src/global_usings.h
> +static const sf::Color DefaultColor = sf::Color::White;
Странно, что ниже ты создаешь constexpr вектора, а тут не constexpr цвет. Неужели нет возможности создать цвет constexpr?

2024-05-08 13:37 UTC, DimaTrushin commented on src/global_usings.h
> +class Axe {
Это что за "топор"? Это оси что-ли? Тогда Axes (оси) или Axis (ось).

2024-05-08 13:37 UTC, DimaTrushin commented on src/configuration.h
> +constexpr char kWindowName[] = "3d-renderer";
У глобальных констант более принят префикс g, чтобы отличать их от просто констант объявленных локально или в классе или еще где-то.

2024-05-08 13:37 UTC, DimaTrushin commented on src/renderer.h
> +        Color color = DefaultColor;
дефолтный цвет можно перенести сюда и назвать background color

2024-05-08 13:37 UTC, DimaTrushin commented on src/renderer.cpp
> +void Renderer::drawFrame(sf::RenderWindow &window) {
Вот это должен быть метод Application.

2024-05-08 13:37 UTC, DimaTrushin commented on src/renderer.cpp
> +void Renderer::renderFrame(sf::RenderWindow &window, const World &world, const Camera &camera) {
Тут две плохие вещи:
1) Название функции врет. Она не просто рендерит фрейм, она еще и отрисовывает его в gui.
2) у тебя есть зависимость в ядре от gui класса. Это максимально плохо. Можно допустить зависимость в обратную сторону, но никак не наоборот. Убери window  как аргумент и возвращай из этого метода построенное изображение (или ссылку на него, если ты не хочешь переаллоцировать буфферы).

2024-05-08 13:37 UTC, DimaTrushin commented on src/renderer.cpp
> +    std::vector<Primitives::Triangle> projectedTriangles = std::move(camera.projectWorldObjects(world));
лишний std::move. Дело в том, что если ты возвращаешь временный объект, он уже rvalue, потому тебе не надо еще раз кастовать его к rvalue.

2024-05-08 13:37 UTC, DimaTrushin commented on src/renderer.cpp
> +    for (const Primitives::Triangle &triangle : projectedTriangles) {
Нарушение уровня абстракции. Я бы видел эту функцию так
```cpp
auto projectedTriangles = camera.projectWorldObjects(world);
renderTriangleOnBuffer(projectedTriangles);
Screen screen = fromBuffer(zbuffer_);
return screen;
```

2024-05-08 13:37 UTC, DimaTrushin commented on src/renderer.cpp
> +        }
Если это сортировка, То выдели в отдельный метод.

2024-05-08 13:37 UTC, DimaTrushin commented on src/renderer.cpp
> +        for (int x = std::max(0, xLeft); x <= std::min(int(screen_.getWidth()) - 1, xRight); ++x) {
Чтобы не делать цикл внутри else, можешь в if сделать return и потом можно for поместить без else.

2024-05-08 13:37 UTC, DimaTrushin commented on src/screen.cpp
> +        data_.emplace_back(sf::Vertex(sf::Vector2f(i, height_ - j), color));
1) Чет я вот тут не понимаю, что происходит. Я ожидал, что ты будешь писать в элемент с индексом i * width + j, а ты добавляешь новый элемент. Это нормально? Что тут происходит?
2) Один конструктор лишний, можно убрать sf::Vertex, потому что в emplace_back ты подставляешь аргументы конструктора, он сам вызовет конструктор внутри себя. Если ты тут вызываешь явно конструктор, все что сделает emplace_back -- вызовет мув конструктор. ТО есть ты потенциально убиваешь оптимизации ради которых он делался, то есть в таком виде он равносилен push_back.

2024-05-08 13:37 UTC, DimaTrushin commented on src/screen.cpp
> +DiscreteVector2 Screen::projectVertexToScreenAndDiscretize(const Primitives::Vertex &v) const {
Странно, что экран сам занимается какими-то проекциями. Я бы ожидал, что экран -- это пассивное хранилище пикселей, которое нужно, чтобы держать в нем результат рендеренга, а всю активную работу выполняет сам рендерер.

2024-05-08 13:37 UTC, DimaTrushin commented on src/screen.h
> +    DiscreteVector2 projectVertexToScreenAndDiscretize(const Primitives::Vertex &v) const;
очень странно.

2024-05-08 13:37 UTC, DimaTrushin commented on src/world.h
> +        const Primitives::Triangle &operator*() const;
добавь еще оператор operator->() const. А то мое чувство прекрасного умирает.

2024-05-08 13:37 UTC, DimaTrushin commented on src/world.h
> +    std::vector<Object> objects_;
Я вот думаю, а не лучше ли было бы хранить сразу вектор всех треугольников тут? И как-то идентифицировать их с объектами? Вообще по-хорошему нужно хранить объекты в структуре данных, которая быстро умеет отсеивать лишние треугольники, но нас это не сильно сейчас заботит.
В целом думаю, что можно оставить и так.

2024-05-08 13:37 UTC, DimaTrushin commented on src/world.h
> +        const World *world_;
Если не хочешь проебаться с nullptr и не возиться с обычными ссылками, то можно хранить std::reference_wrapper<const World>. Он как и обычный указатель обеспечиват классу value semantics, но при этом он гарантирует, что он как ссылка всегда не nullptr.

2024-05-08 13:37 UTC, DimaTrushin commented on src/world.cpp
> +World::ConstIterator World::begin() const { return World::ConstIterator(this, 0, 0); }
внутри метода класса не надо указывать квалификатор класса, то есть можно написать просто
```cpp
return ConstIterator(this, 0, 0);
```
Так как это код метода класса, то все имена внутри класса автоматически видны внутри метода, это относится и к именам аргументов.

2024-05-08 13:37 UTC, DimaTrushin commented on src/primitives.h
> +    friend Vertex operator*(const Matrix4 &m, const Vertex &v);
Добавсь inplace и имплементируй этот через него.

2024-05-08 13:37 UTC, DimaTrushin commented on src/primitives.h
> +            const Vector4 &operator*() const;
Я так понимаю, что вся суть лишь в том, чтобы подменить итератор и возвращать по звездочке именно вершину и все.

2024-05-08 13:37 UTC, DimaTrushin commented on src/primitives.h
> +        const Container &host_;
лучше используй std::reference_wrapper<const Container>, так ты получишь value semantics.

2024-05-08 13:37 UTC, DimaTrushin commented on src/primitives.cpp
> +Triangle Triangle::linearTransform(const Matrix4 &transformMatrix, const Triangle &triangle) {
Порядок методов в cpp файле должен быть точно такой же как в h файле!

2024-05-08 13:37 UTC, DimaTrushin commented on src/off_loader.cpp
> +        throw(std::invalid_argument(std::string("Only ") + configuration::kModelExtension +
Плохая тема контролировать work flow с помощью exception. Ты могла бы просто вернуть код ошибки и проверить его if-ом. В итоге, ты либо как сейчас падаешь вплоть до main, где идет обработка исключений (если она тем есть, а то и вовсе улетаешь в ОС), либо должна прямо в том месте где ты зовешь эту функцию ставить try/catch блок. И возникает вопрос "схуяли?" если можно просто вернуть код ошибки и ретернуть. Вообще если получатель исключения живет на уровень ниже, это ошибка дизайна. Если твоя программа падает по исключению только из-за неверного формата файла, это так себе решение, но видимо тут это намерено. И раз ты сама кидаешь исключения, их все же надо перехватывать.

2024-05-08 13:37 UTC, DimaTrushin commented on src/off_loader.cpp
> +    bool isFirstLine = true;
Ты нигде это не используешь

2024-05-08 13:37 UTC, DimaTrushin commented on src/off_loader.cpp
> +    file.close();
Не закрывай файловые потоки руками, их закроет деструктор.

2024-05-08 13:37 UTC, DimaTrushin commented on src/off_loader.cpp
> +    while (getline(file, line)) {
Все три цикла внизу в строках 21, 33 и 43 выглядят как отдельные функции.

2024-05-08 13:37 UTC, DimaTrushin commented on src/off_loader.cpp
> +bool Loader::checkBlankLinesAndComments(const std::string &line) const {
Если функция возвращает bool, то ее название должно начинаться либо с is/are либо с has/have. Иначе не понятно что именно эта функция чекает.

2024-05-08 13:37 UTC, DimaTrushin commented on src/off_loader.cpp
> +    if (r >= 0 && r <= 1 && g >= 0 && g <= 1 && b >= 0 && b <= 1 && a >= 0 && a <= 1) {
Почему функция конвертации проверяет прекондишнс на свои аргументы? Она опять делает больше чем надо.

2024-05-08 13:37 UTC, DimaTrushin commented on src/off_loader.cpp
> +    bool aDefault = false;
Что это за флаг?

2024-05-08 13:37 UTC, DimaTrushin commented on src/camera.cpp
> +    projectionMatrix_ = getProjectionMatrix();
что за питонячий стиль? Перенеси в список инициализации.

2024-05-08 13:37 UTC, DimaTrushin commented on src/camera.cpp
> +    // glm matrices written by columns
вот это пример хорошего комментария.

2024-05-16 11:13 UTC, cutehater commented on .gitignore
> +src/MakeFile
Вообщем, я не справилась это сделать. Как я поняла, потому что локально ставится почему-то только 14 версия clang-format как самая новая, а это правило работает, начиная с 16. Но я нашла способ через vscodовский файлик settings.json сделать. И в .clang-format это правило на всякий случай тоже добавила (вернее, оно и до этого там было).

2024-05-17 08:48 UTC, cutehater commented on src/off_loader.cpp
> +    if (r >= 0 && r <= 1 && g >= 0 && g <= 1 && b >= 0 && b <= 1 && a >= 0 && a <= 1) {
Это не прекондишнс, просто цвет может быть записан либо даблом от 0 до 1, либо целым числом от 0 до 255. И в первом случае надо домножать на 255, во втором нет. Но прекондишнс, пожалуй, действительно надо добавить, чтобы проверить, что либо то, либо другое.

2024-05-17 08:49 UTC, cutehater commented on src/off_loader.cpp
> +    bool aDefault = false;
Цвет может быть записан либо 3, либо 4 компонентами. Флаг aDefault показывает, передали ли нам 4 а-координату цвета.

2024-05-17 11:58 UTC, cutehater commented on src/global_usings.h
> +static const sf::Color DefaultColor = sf::Color::White;
Я так поняла, к static constexpr выражениям класса (типа как в Axis) это не относится. В остальных местах убрала.

2024-05-17 12:03 UTC, cutehater commented on src/global_usings.h
> +static const sf::Color DefaultColor = sf::Color::White;
Она ещё для дефолтного цвета Vertex используется. А дефолтный конструктор Vertex используется в нескольких местах, когда, например, надо создать array<Vertex, 3>, туда записать вершины старого треугольника, к которым применили какое-то преобразование и потом по этому array создать новый треугольник. 
В общем-то, во всех этих местах всё равно, какой цвет вершины назначать, но для приличия, наверное, лучше в дефолтном конструкторе всё-таки назначать дефолтный цвет, поэтому я решила оставить так.

2024-05-17 12:05 UTC, cutehater commented on src/global_usings.h
> +static const sf::Color DefaultColor = sf::Color::White;
К сожалению, нет, перед sf::Color нельзя поставить квалификатор constexpr.

2024-05-17 12:08 UTC, cutehater commented on src/object.h
> +    Object() = default;
Незачем, убрала

2024-05-17 14:06 UTC, cutehater commented on src/application.h
> +    void addObject(Object &&object);
Ну я сделала немного по-другому: вместо FunctionPtr = Signature* 
FunctionPtr = std::function<Signature>.
Это потому что кроме примеров с кубами и пирамидкой, которые полностью сами себя создают, мы хотим ещё и из произвольного файла выгружать модельки. То есть надо, чтобы инициализатор как-то получил имя файла в качестве параметра. Можно, конечно, создать отдельный инициализатор прямо в examples/load_model.cpp, но это как-то костыльно, пользователь тогда должен из main напрямую с world работать. Более подходящим мне показалось поменять сигнатуру так, чтобы была возможность в качестве инициализатора передавать лямбды - тогда с передачей каких-то параметров внутрь инициализатора проблем нет.

2024-05-17 14:26 UTC, cutehater commented on src/storage2d.h
> +    Storage2D(size_t rows, size_t cols) : rows_(rows), cols_(cols), data_(rows * cols){};
Нет, он везде применяется, просто у меня максимальная длина строчки чуть больше, чем дефолтная (где-то какой-то монстр получался с дефолтной, уже не помню где, поэтому подправила).

2024-05-17 14:30 UTC, cutehater commented on src/vector4.cpp
> +Vector4::Vector4(const glm::dvec4 &v) : glm::dvec4(v.x, v.y, v.z, v.w) {}
Резонно

2024-05-17 14:46 UTC, cutehater commented on src/storage2d.h
> +    size_t cols_;
Как будто один лишний инт в масштабе всей программы нулевое влияние оказывает на производительность/память, а каждый раз восстанавливать rows_ менее приятно, чем один раз запомнить его и потом использовать напрямую.

2024-05-17 15:16 UTC, cutehater commented on src/renderer.h
> +        Color color = DefaultColor;
Ответила в комментарии в другом issue про дефолтный цвет

2024-05-18 11:45 UTC, cutehater commented on src/primitives.h
> +            const Vector4 &operator*() const;
Ну не саму вершину, а только её координату, но да

2024-05-18 11:53 UTC, cutehater commented on src/screen.cpp
> +        data_.emplace_back(sf::Vertex(sf::Vector2f(i, height_ - j), color));
Логически (да и, наверное, по производительности тоже - память изначально аллоцируется под width * height элементов) в данном случае без разницы, каждый раз добавлять новые элементы или перезаписывать существующие - результат отрисовки будет одинаковым. Но, наверное, действительно, чтобы понятнее было, что проиходит, лучше пользоваться вторым вариантом.

2024-05-18 12:03 UTC, cutehater commented on src/renderer.cpp
> +    for (const Primitives::Triangle &triangle : projectedTriangles) {
Ну там как-то не очень получается: zbuffer это абстракция для рендерера, поэтому логично её там определять, при этом метод формирования экрана из z-буфера логично сделать методом Screen, но тогда возникает циклическая зависимость, потому что renderer.h импортирует screen.h, а screen.h импортирует renderer.h. В общем, я не придумала чего-то лучше, чем сделать метод fillScreen() в Renderer и перенести туда.

2024-05-29 22:35 UTC, merged